### ISSUE TITLE
Caching does not take timeout into account

### ISSUE THREAD

**Issue by pitrou** [mwilliamson/locket.py#5]
This means your codebase can't sometimes take a lock in a blocking way and sometimes in a non-blocking way.
```python
>>> lock1 = locket.lock_file("/tmp/xxx.lock")
>>> lock2 = locket.lock_file("/tmp/xxx.lock", timeout=0)
>>> lock1 is lock2
True
>>> lock2.acquire()
>>> lock2.acquire()
[ hangs until Ctrl-C ]
```

The solution would be to allow overriding timeout on acquire() instead. What do you think @mwilliamson?

**Comment by mwilliamson** [comment]
Hmm, the fact that the locks are cached based just on the filename despite other arguments being available is definitely wrong. Before I can give a helpful reply though, I need to remember why that cache exists in the first place!

**Comment by mwilliamson** [comment]
Right, it's to make sure that the locks aren't re-entrant, otherwise a process could create two locks for the same path and the call to `acquire()` would pass on both.

It seems to me that the wrong thing is being cached. Specifically, for the threading locks, we just want to cache the `threading.Lock` instance, while for the actual file lock we want to cache the file.
